#!/bin/sh

if [ -n "$EX4DEBUG" ]; then
  echo "now debugging $0 $@"
  set -x
fi

[ -x /usr/lib/exim4/exim4 ] || exit 0

[ -f /etc/default/exim4 ] && . /etc/default/exim4

if [ "${QUEUERUNNER}" != "no" ] ; then
# Flush exim queue
	/usr/sbin/exim4 -qqf ${QUEUERUNNEROPTIONS} ${COMMONOPTIONS}
fi
