#!/bin/sh

set -e

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d avahi-daemon remove >/dev/null
fi
# End automatically added section


if [ "$1" = "purge" ] ; then
    deluser --quiet --system avahi > /dev/null || true
    delgroup --quiet --system avahi > /dev/null || true
    # Cleanup /var/run/avahi-daemon, see #448539
    f=/var/run/avahi-daemon
    if [ -d "$f" ]; then
        rmdir "$f" || { chown root:root "$f" && chmod 00700 "$f"; }
    fi
fi

