#!/bin/bash

set -e

case "$1" in
    purge)
	rm -f /etc/bash_completion
        # let's remove old bash-completion conffiles
        for f in $(find /etc/bash_completion.d/ -type f -name "*.dpkg-*"); do
            dpkg-maintscript-helper rm_conffile ${f%.dpkg-*} 1:1.3-1 -- "$@"
        done
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
