#!/bin/sh -e

do_mpd_stop () {
    if [ -x /etc/init.d/mpd ]; then
        if [ -x /usr/sbin/invoke-rc.d ]; then
            invoke-rc.d mpd stop
        else
            /etc/init.d/mpd stop
        fi
    fi
}

case "$1" in
    remove|deconfigure)
        do_mpd_stop
        ;;
    upgrade|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac


