#!/bin/sh

set -e

if [ "$1" = "upgrade" ] && dpkg --compare-versions "$2" lt "1.5.19-2" ; then
	MD5SUM=$(md5sum /etc/Muttrc.d/smime-paths.rc | cut -d ' ' -f 1)
	if [ "$MD5SUM" = "185414b78b332a662500719a179778c5" ] ; then
		echo "Removing obsolete config file /etc/Muttrc.d/smime-paths.rc"
		rm /etc/Muttrc.d/smime-paths.rc
	else
		echo "Not removing modified obsolete config file /etc/Muttrc.d/smime-paths.rc"
	fi
fi



exit 0
