#!/bin/sh

set -e
if [ "$1" = purge ]; then
	rm -rf /etc/samba/ /var/cache/samba/ /var/lib/samba/ /var/run/samba/
	if [ -x "`which ucf 2>/dev/null`" ]; then
		ucf --purge /etc/samba/smb.conf
	fi
	if [ -x "`which ucfr 2>/dev/null`" ]; then
		ucfr --purge samba-common /etc/samba/smb.conf
	fi
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

