#! /bin/sh
# pkg-config wrapper for cross-building
# Sets pkg-config search path to target arch path only.

triplet=`basename $0 | sed -e 's:-pkg-config::'`
PKG_CONFIG_LIBDIR=/usr/${triplet}/lib/pkgconfig pkg-config $@
