#!/bin/sh
set -e

echo '-- rpcinfo --' >&3
rpcinfo -p >&3

echo '-- /etc/default/nfs-common --' >&3
cat /etc/default/nfs-common|grep -v -e '^\#' -e '^$' >&3

echo '-- /etc/idmapd.conf --' >&3
cat /etc/idmapd.conf|grep -v -e '^\#' -e '^$' >&3

echo '-- /etc/fstab --' >&3
cat /etc/fstab|grep nfs >&3

echo '-- /proc/mounts --' >&3
cat /proc/mounts|grep nfs >&3
